# Generated by Django 3.2 on 2021-05-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.CharField(default='USING', max_length=200),
        ),
    ]
